# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://familiafrozen.com
title: Fredi, Mari e Bella - Família Frozen
email: familiafrozen@gmail.com
description: Somos Fredi, Mari e Bella, carinhosamente conhecidos como Família Frozen.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/fredimariebella
